config/routes.rb
Rails.application.routes.draw do

   get 'contacts' => 'contacts#index'
   get 'contacts/new' => "contacts#new" 
   get 'contacts/:id' => 'contacts#show', as: :contact
   
   root 'contacts#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

   def index
      @contacts = Contact.all
   end

   def show
      @contact = Contact.find( params[:id] )
   end

   def new
      @contact = Contact.new
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<% @contacts.each do |contact| %>
   <p><%= link_to contact.name, contact_path( contact.id ) %></p>
<% end %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= form_for @contact do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :phone %>
    <%= f.text_field :phone, size: 15 %>

    <%= f.label :email %>
    <%= f.text_field :email, size: 20 %>

    <%= f.submit "Create" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tacta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<br><br>
<hr>

<%= link_to "[All Contacts]", root_path %>

</body>
</html>